### ISSUE TITLE
Broken Pipe Error --- Jobs fail when Bam is above ~100Gb

### ISSUE THREAD

**Issue by maxfieldk** [santiago-es/Telometer#3]
Hi Santiago,
Just a heads up - I've managed to run Telometer on many samples (mostly successfully!) and have noticed that Bam files are above ~100Gb I get a string of BrokenPipeErrors which ultimately produce an out of memory event (I am running on a cluster with 240Gb of RAM). I've documented an instance of this below. For now one can get around this by splitting up their large bam files.

ERROR MESSAGE

Process ForkPoolWorker-43:
Traceback (most recent call last):
  File "/users/mkelsey/anaconda/telometer/lib/python3.8/multiprocessing/pool.py", line 131, in worker
    put((job, i, result))
  File "/users/mkelsey/anaconda/telometer/lib/python3.8/multiprocessing/queues.py", line 368, in put
    self._writer.send_bytes(obj)
  File "/users/mkelsey/anaconda/telometer/lib/python3.8/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/users/mkelsey/anaconda/telometer/lib/python3.8/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header)
  File "/users/mkelsey/anaconda/telometer/lib/python3.8/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/users/mkelsey/anaconda/telometer/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/users/mkelsey/anaconda/telometer/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/users/mkelsey/anaconda/telometer/lib/python3.8/multiprocessing/pool.py", line 136, in worker
    put((job, i, (False, wrapped)))
  File "/users/mkelsey/anaconda/telometer/lib/python3.8/multiprocessing/queues.py", line 368, in put
    self._writer.send_bytes(obj)
  File "/users/mkelsey/anaconda/telometer/lib/python3.8/multiprocessing/connection.py", line 200, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/users/mkelsey/anaconda/telometer/lib/python3.8/multiprocessing/connection.py", line 404, in _send_bytes
    self._send(header)
  File "/users/mkelsey/anaconda/telometer/lib/python3.8/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
slurmstepd: error: Detected 1 oom_kill event in StepId=3897771.0. Some of the step tasks have been OOM Killed.
srun: error: node1909: task 0: Out Of Memory

**Comment by santiago-es** [comment]
Glad it's been working for you!

Yes, the memory / storage can be an issue and the main page doesn't really comment on it yet. 

If you try to pipe minimap2 directly to Samtools view / sort the memory requirement balloon very quickly and on our HPC I have to use a memory partition with >300 GB of RAM for some files. 

Splitting it up like in the instructions decreases the memory requirement, but the storage of the BAMs then becomes an issue. Two solutions: reduce the number of supplementary alignments. The script already only keeps the telomere measurement from the alignment with the highest MAPQ in the case of multiple alignments, so reducing -N to 0 should be fine -- I used to be afraid of missing telomeres because a supplementary alignment was closer to the real telomere but the main alignment was not,but I'm not sure this fear is founded. Second option (which is what I do) is to write SAM and unsorted BAM to a /tmp/ directory with very high storage and then delete them after the next processing step is done. Finally, gzip the sorted bam. 

For the ease of sharing data for a future publication, I also suggest writing a simple Python script that extracts only the reads associated with telomere measurements (can use the read id column from the telometer output to help you) from the sorted bam into a new bam, sort and index, gzip, and then you have a lightweight bam that can be used for publication. Can go back and do the same for the raw fastq if you concatenate the fastqs as well. If you plan on publishing an experiment, this will save you time later.

**Comment by maxfieldk** [comment]
Thank you @santiago-es !
